### ISSUE TITLE
ダミーデータの作成

### ISSUE THREAD

**Issue by KRei0** [iBeeM-12/front_environment#3]
2，3個ほどのダミーデータを作成する。
ダミーデータの内容に関してはコメント等で、提案して下さると嬉しいです。

内容1(プロフィール関係)
・名前
・ID
・状態
・画像データ(自身のアイコン)
・概要

内容2(状態表示)
・勉強中
・暇
・寝る
・学校
・バイト

**Comment by KRei0** [comment]
必要分＃５で作成しました

**Comment by KRei0** [comment]
色々散らばっているので、調整の必要があると思います

**Comment by KRei0** [comment]
色々散らばっているので、調整の必要があると思います

**Comment by zomatype** [comment]
ダミーデータで必要なもの
・状態表示一覧(状態表示のアイコン)
・グループ一覧(グループ名,グループサムネ)
・グループメンバー一覧(メンバーの名前,サムネ,)
・グループメンバー状態表示一覧
